spring.application.name=finances

# ===================================================================
# CONNECTION TO DB
# ===================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/finanzas_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===================================================================
# CONFIG JPA / HIBERNATE
# ===================================================================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=finance_db.sql
